"""Trading Signal Model."""

from sqlalchemy import Column, String, Float, DateTime, Text, Index, Enum as SQLEnum, ForeignKey
from sqlalchemy.orm import relationship
from enum import Enum
from datetime import datetime

from .base_model import BaseModel


class SignalType(str, Enum):
    """Signal type enum."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class SignalStatus(str, Enum):
    """Signal status enum."""

    ACTIVE = "active"
    EXECUTED = "executed"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


class Signal(BaseModel):
    """
    Trading signal model.

    Stores technical analysis signals generated by the system.
    """

    __tablename__ = "signals"

    # User ownership - CRITICAL for multi-user isolation
    user_id = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # Signal details
    symbol = Column(String(20), nullable=False, index=True)
    timeframe = Column(String(10), nullable=False)
    signal_type = Column(SQLEnum(SignalType, name="signal_type"), nullable=False)
    status = Column(SQLEnum(SignalStatus, name="signal_status"), nullable=False, default=SignalStatus.ACTIVE)

    # Price levels
    entry_price = Column(Float, nullable=False)
    current_price = Column(Float, nullable=True)
    target_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)

    # Confidence and metadata
    confidence = Column(Float, nullable=False)  # 0-100
    strategy = Column(String(100), nullable=True)
    description = Column(Text, nullable=True)

    # Timing
    generated_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)
    executed_at = Column(DateTime, nullable=True)

    # Link to trading decision (optional - signal can exist without decision)
    trading_decision_id = Column(String(36), ForeignKey('trading_decisions.id'), nullable=True)

    # Relationship
    trading_decision = relationship("TradingDecision", back_populates="signals")

    # Indexes - IMPORTANT: user_id must be first for query performance
    __table_args__ = (
        Index('idx_signal_user_id', 'user_id'),
        Index('idx_signal_user_symbol_timeframe', 'user_id', 'symbol', 'timeframe'),
        Index('idx_signal_status', 'status'),
        Index('idx_signal_generated_at', 'generated_at'),
    )

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            "id": str(self.id),
            "user_id": str(self.user_id),
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "signal_type": self.signal_type.value if self.signal_type else None,
            "status": self.status.value if self.status else None,
            "entry_price": self.entry_price,
            "current_price": self.current_price,
            "target_price": self.target_price,
            "stop_loss": self.stop_loss,
            "confidence": self.confidence,
            "strategy": self.strategy,
            "description": self.description,
            "trading_decision_id": str(self.trading_decision_id) if self.trading_decision_id else None,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self) -> str:
        """String representation."""
        return (
            f"<Signal(symbol={self.symbol}, type={self.signal_type}, "
            f"confidence={self.confidence}, status={self.status})>"
        )
